name:  Deploy API

env:
  AZURE_WEBAPP_NAME: gimnasiojena
  AZURE_WEBAPP_PACKAGE_PATH: './GimnasioJena.UI'
  DOTNET_VERSION: '8.0'

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'BD/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Replace connection string in appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/appsettings.json'
        env:
          ConnectionStrings.BD: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

      - name: Restore, Build and Publish
        run: |
          dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --configuration Release --no-restore
          dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -c Release -o ./publish --no-restore

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
 esto es bien asi?
