name: Deploy API

env:
  AZURE_WEBAPP_NAME: gimnasiojena
  PROJECT_PATH: './GimnasioJena.UI'
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'BD/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore ./GimnasioJena.sln

      - name: Replace connection string in Web.config
        shell: powershell
        run: |
          $configPath = "./GimnasioJena.UI/Web.config"
          $secretConn = "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
          
          if (Test-Path $configPath) {
              $content = Get-Content $configPath -Raw
              # Reemplaza dinámicamente cualquier texto dentro de connectionString="..." por el secreto de Azure
              $content = $content -replace 'connectionString="[^"]+"', ('connectionString="' + $secretConn + '"')
              Set-Content -Path $configPath -Value $content
              Write-Host "Cadena de conexión reemplazada con éxito en Web.config."
          } else {
              Write-Error "No se encontró el archivo Web.config en la ruta especificada."
              exit 1
          }

      - name: Build and Package Web App
        run: |
          msbuild ${{ env.PROJECT_PATH }} /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:OutDir=./build_output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './build_output/_PublishedWebsites/GimnasioJena.UI'
