name: Deploy Database to Azure SQL

env:
  BD_FOLDER: 'Proyecto-Gimnasio-Jena/BD'  # Carpeta del proyecto de base de datos
  BD_PROJECT: 'BD.sqlproj'                 # Nombre del archivo .sqlproj
  BD_DACPAC: 'BD.dacpac'                   # Nombre del dacpac generado (normalmente igual al proyecto)
  SOLUTION_FILE: 'Proyecto-Gimnasio-Jena/GimnasioJena.sln'          # Nombre del archivo .sln (para restore de NuGet)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Proyecto-Gimnasio-Jena/BD/**'          # Debe coincidir con el valor de BD_FOLDER
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy-database:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "${{ env.SOLUTION_FILE }}"

      - name: Build Database Project
        run: msbuild "${{ env.BD_FOLDER }}/${{ env.BD_PROJECT }}" /p:Configuration=Release /p:OutputPath="./bin/Release/"
        shell: cmd

      - name: Deploy to Azure SQL Database
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "${{ env.BD_FOLDER }}/bin/Release/${{ env.BD_DACPAC }}"
          action: 'publish'
          arguments: '/p:DropObjectsNotInSource=false /p:BlockOnPossibleDataLoss=true'
